version: '3'

services:
  server:
    container_name: server
    build: . 
    # is the same as
    # context: .
    # dockerfile: Dockerfile
    #
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/
    ports:
      - "3000:3000"
    restart: always

  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongoVolume:/data/db

volumes: 
  mongoVolume:
        
  